### ISSUE TITLE
Details on performing inference

### ISSUE THREAD

**Issue by Nicholas-Autio-Mitchell** [facebookresearch/WSL-Images#1]
I am trying to run a variant of your model from [Pytorch Hub](https://pytorch.org/hub).

I couldn't find any details in your paper (or the papers you mention) on exactly how I should prepare a standard image to get meaningful results.

I know the batch shape must be `(batch_size, 3, 224, 224)`, and I also read in one of [your linked papers](https://arxiv.org/pdf/1706.02677.pdf):

> The network input image is a 224×224 pixel random crop from an augmented image or its horizontal flip. The input image is normalized by the per-color mean and standard deviation, as in [12].

However, even after applying this to my basic images, I am getting a consistently incorrect prediction for a simple case (German Shepherd).

Is there any more information or code you can point to that will help?

**Comment by dkm2110** [comment]
Hi Mitchell

Actually, a sample example is given here
https://pytorch.org/hub/facebookresearch_WSL-Images_resnext/ . Please
follow this exactly. If you still face discrepancies, and can share the
image and some of ur code that would be helpful.

Dhruv

**Comment by Nicholas-Autio-Mitchell** [comment]
Great, thanks!  :smile: 

Maybe you could include that link in the README, instead of the generic PyTorch Hub page?

**Comment by FangmingZhou** [comment]
great! I actually need this example link for my task! It would be better if the link can be show in the readme.md.  :)
